### PR TITLE
esc_temp & 3 wheel settings over ui

### PR DESCRIPTION
**Pull request by ggaljoen**

### CODE REVIEW

**Comment by ggaljoen** [comment]
also dropped st-link changed to CMSIS-DAP

**Comment by ggaljoen** [comment]
Maybe better to make a diff and just import that one in the main branch ? that way my 2 dummy commits would be elimintated.

**Comment by casainho** [comment]
Please make a git squash first. Look on google. The. You will only have 1 commit on this pull request.

**Comment by ggaljoen** [comment]
thank you, will figure it out.
Bummer; wheel size and perimeter can be set but are not accepted ???

**Pull request closed without merging**
